### ISSUE TITLE
Crashes when breaking Networking Cable with PolyMC installed

### ISSUE THREAD

**Issue by Zekiu** [PolymerPorts/cc-restitched#1]
## Useful information to include:
 - Minecraft version: 1.19
 - CC: Restitched version: 1.101.0
 - Logs: 
[latest.log](https://github.com/PolymerPorts/cc-restitched/files/8940029/latest.log)
[crash-2022-06-20_12.58.34-server.txt](https://github.com/PolymerPorts/cc-restitched/files/8940030/crash-2022-06-20_12.58.34-server.txt)

 - Detailed reproduction steps: 
1. Place Networking Cable
2. Break Networking Cable
3. Server crashes

- Mods used:
PolyMc 5.1.0
Polymer 0.2.1
Fabric API 0.56.1
CC-Restitched Polymer Port 1.101.0

**Comment by Patbox** [comment]
I guess PolyMc changed it's api and I didn't update polymer to it. Will release fixed polymer version soon

**Comment by Patbox** [comment]
Install this version of polymer to fix that: https://modrinth.com/mod/polymer/version/0.2.2+1.19
I will close this issue once I update one bundled with this mod
