### ISSUE TITLE
How to guide

### ISSUE THREAD

**Issue by j00w33** [PolymerPorts/cc-restitched#2]
Not really a feature request or a bug report, but I'm just confused as to how this works. I added it to my server mods folder but there isn't anything that shows up in game. It's server side only, correct? Are there settings in the config that are needed to enable it?

**Comment by Patbox** [comment]
It should work out of the box. To see recipes you want to use something like polydex. To open computer, just click it after placing (you need to be on ground through). 

Then just: https://github.com/PolymerPorts/cc-restitched#how-to-use-uis

**Comment by j00w33** [comment]
Got it. The recipes weren't showing in REI. A quick google to the OG dev page showed me the recpies, and once I got that, it worked. Polydex doesn't show anything. maybe i'm doing it wrong ¯\_(ツ)_/¯
