### ISSUE TITLE
rebase to CC:T Fabric

### ISSUE THREAD

**Issue by Merith-TK** [PolymerPorts/cc-restitched#3]
With the recent change to CC:T Fabric on most servers, it would be ideal for the code base to reflect this, 

I am not saying support forge (gods forbid that headache as you would have to port Polymer), but having an CC:T version of this where changes can simply be pulled from upstream would be nice as CC:R is no longer *actively* maintained.

**Comment by Patbox** [comment]
My plan is to rebase it on that, but this still requires a lot of manual work (so time) to make it work. Possibly it could be implemented with mixins instead of forking original versions, lowering maintance cost

**Comment by Merith-TK** [comment]
If mixins can be done, maybe make a guide using CC as an example due to the overall semi-complexity? so that other mod developers can potentially implement Polymer Mixins in their mods, I know I would

**Comment by Patbox** [comment]
Thats still only maybe, depends how much pain it will be to implement

**Comment by Patbox** [comment]
https://github.com/PolymerPorts/cc-tweaked-patch
