### ISSUE TITLE
1.20 update?

### ISSUE THREAD

**Issue by DaveyL2013** [PolymerPorts/cc-restitched#4]
Eventually? Or is this abandoned? There haven't been any commits for over half a year now... I don't care if it takes a while, I'd just like to know if it's happening at all. Thanks!

**Comment by Patbox** [comment]
I want to update it to 1.20(.2?), but it will likely work as a patch mod on top of CC:Tweaked instead of being full on fork. Main problem here is that CC:Restirched is abandoned, which makes it harder to update

**Comment by skunkmommy** [comment]
bump, i don't get command block logic but cc command computers let me use lua. having that on vanilla servers would be cool.
i don't play on many servers let alone any that this would reasonably apply to, but still. i see the value.

**Comment by nycki93** [comment]
@spudpiggy, the problem is that this is based on [CC:Restitched](https://www.curseforge.com/minecraft/mc-mods/cc-restitched), which has been discontinued. It would have to be rewritten to work with [CC:Tweaked](https://modrinth.com/mod/cc-tweaked) instead, I think.

**Comment by Patbox** [comment]
The replacement / rework rebased on top of CC: Tweaked isworked on

**Comment by skunkmommy** [comment]
[here](https://modrinth.com/mod/cc-polymer)'s the mod @Patbox was referring to

**Comment by Patbox** [comment]
https://github.com/PolymerPorts/cc-tweaked-patch or if someone wants the github!
